Repository dbudwin/RoboHome-Web, pull requests merged in 2018-10, with the labels that each got.

#159 Use SweetAlert to add confirmation after clicking delete
  resources/views/devices.blade.php
  tests/Browser/DevicesTest.php
Labels: :gem: Enhancement

#160 Update composer dependencies
  .travis.yml
  composer.json
  composer.lock
Labels: :lock: Security

#166 Custom 404 error page
  public/css/404.css
  resources/views/errors/404.blade.php
  tests/Browser/404Test.php
Labels: :tada: Feature

#165 Add static fixed footer to bottom
  resources/views/devices.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/footer.blade.php
  tests/Browser/404Test.php
  tests/Browser/DevicesTest.php
  tests/Browser/IndexTest.php
Labels: :tada: Feature
